# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=200)),
                ('autorisations', models.IntegerField(default=0)),
            ],
        ),
    ]
